version: '3.4'

services:
  rentscooter_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_rentscooter_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  rentscooter_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_rentscooter_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  rentscooter_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_rentscooter_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  rentscooter_api:
    ports:
      - "10000:80"
    networks:
      - shared_rentscooter_net
    env_file:
      - env.api
      
  rentscooter_identity:
    ports:
      - "10001:80"
    networks:
      - shared_rentscooter_net
    env_file:
      - env.identity

  rentscooter_worker_1:
    networks:
      - shared_rentscooter_net
    env_file:
      - env.worker

  rentscooter_worker_2:
    networks:
      - shared_rentscooter_net
    env_file:
      - env.worker

  rentscooter_web:
    ports:
      - "10002:80"
    networks:
      - shared_rentscooter_net

networks:
  shared_rentscooter_net:
    name: rentscooter
    driver: bridge